import { Exercise } from './types';

// Базовые упражнения, которые нельзя удалить
export const BASE_EXERCISES: Exercise[] = [
    { id: '38', name: 'Становая тяга', group: 'back', isHidden: false, isProtected: true },
    { id: '2', name: 'Приседания со штангой', group: 'legs', isHidden: false, isProtected: true },
    { id: '3', name: 'Жим штанги лёжа', group: 'chest', isHidden: false, isProtected: true },
    { id: '1', name: 'Тяга рычажная в тренажёре', group: 'back', isHidden: false },
    { id: '4', name: 'Армейский жим', group: 'shoulders', isHidden: false },
    { id: '5', name: 'Тяга штанги в наклоне', group: 'back', isHidden: false },
    { id: '6', name: 'Жим гантелей лёжа', group: 'chest', isHidden: false },
    { id: '7', name: 'Подтягивания широким хватом', group: 'back', isHidden: false },
    { id: '8', name: 'Тяга блока к поясу', group: 'back', isHidden: false },
    { id: '9', name: 'Жим штанги стоя', group: 'shoulders', isHidden: false },
    { id: '10', name: 'Французский жим', group: 'triceps', isHidden: false },
    { id: '11', name: 'Подъём штанги на бицепс', group: 'biceps', isHidden: false },
    { id: '12', name: 'Приседания фронтальные', group: 'legs', isHidden: false },
    { id: '13', name: 'Румынская тяга', group: 'legs', isHidden: false },
    { id: '14', name: 'Шраги со штангой', group: 'shoulders', isHidden: false },
    { id: '15', name: 'Жим ногами в тренажёре', group: 'legs', isHidden: false },
    { id: '16', name: 'Сгибания ног лёжа', group: 'legs', isHidden: false },
    { id: '17', name: 'Разгибания ног сидя', group: 'legs', isHidden: false },
    { id: '18', name: 'Подъём на носки в тренажёре', group: 'legs', isHidden: false },
    { id: '19', name: 'Тяга гантели одной рукой', group: 'back', isHidden: false },
    { id: '20', name: 'Жим штанги узким хватом', group: 'triceps', isHidden: false },
    { id: '21', name: 'Разведения гантелей лёжа', group: 'chest', isHidden: false },
    { id: '22', name: 'Пуловер со штангой', group: 'chest', isHidden: false },
    { id: '23', name: 'Отжимания на брусьях', group: 'triceps', isHidden: false },
    { id: '24', name: 'Подъём гантелей через стороны', group: 'shoulders', isHidden: false },
    { id: '25', name: 'Тяга нижнего блока', group: 'back', isHidden: false },
    { id: '26', name: 'Жим Арнольда', group: 'shoulders', isHidden: false },
    { id: '27', name: 'Сгибания рук со штангой', group: 'biceps', isHidden: false },
    { id: '28', name: 'Разгибания рук на блоке', group: 'triceps', isHidden: false },
    { id: '29', name: 'Приседания в Гакк-машине', group: 'legs', isHidden: false },
    { id: '30', name: 'Гудморнинг', group: 'legs', isHidden: false },
    { id: '31', name: 'Тяга Т-грифа', group: 'back', isHidden: false },
    { id: '32', name: 'Жим в хаммере', group: 'chest', isHidden: false },
    { id: '33', name: 'Сведения рук в тренажёре', group: 'chest', isHidden: false },
    { id: '34', name: 'Тяга верхнего блока за голову', group: 'back', isHidden: false },
    { id: '35', name: 'Французский жим сидя', group: 'triceps', isHidden: false },
    { id: '36', name: 'Молотковые сгибания', group: 'biceps', isHidden: false },
    { id: '37', name: 'Наклонный жим гантелей', group: 'chest', isHidden: false },
    { id: '39', name: 'Жим штанги сидя', group: 'shoulders', isHidden: false },
    { id: '40', name: 'Разгибания рук с гантелью', group: 'triceps', isHidden: false },
    { id: '41', name: 'Подъём штанги на скамье Скотта', group: 'biceps', isHidden: false },
    { id: '42', name: 'Приседания с гирями', group: 'legs', isHidden: false },
    { id: '43', name: 'Тяга гири к подбородку', group: 'shoulders', isHidden: false },
    { id: '44', name: 'Жим платформы одной ногой', group: 'legs', isHidden: false },
    { id: '45', name: 'Сгибания рук на скамье Скотта', group: 'biceps', isHidden: false },
    { id: '46', name: 'Разгибания рук из-за головы', group: 'triceps', isHidden: false },
    { id: '47', name: 'Тяга штанги к подбородку', group: 'shoulders', isHidden: false },
    { id: '48', name: 'Жим штанги в Смите', group: 'chest', isHidden: false },
    { id: '49', name: 'Приседания в Смите', group: 'legs', isHidden: false },
    { id: '50', name: 'Тяга верхнего блока прямыми руками', group: 'back', isHidden: false },
];

// Табы групп мышц
export const MUSCLE_GROUP_TABS = [
    { value: 'all', label: 'Все' },
    { value: 'chest', label: 'Грудь' },
    { value: 'back', label: 'Спина' },
    { value: 'legs', label: 'Ноги' },
    { value: 'biceps', label: 'Бицепс' },
    { value: 'triceps', label: 'Трицепс' },
    { value: 'shoulders', label: 'Плечи' },
] as const;

export const DEFAULT_WHEEL_SETTINGS = {
    duration: 10,
    turnoverRange: [10, 20] as [number, number],
};
